services:
    Akyos\SystempayBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Tests,Kernel.php}'
        autowire: true
        autoconfigure: true
        public: true

    akyos.systempay:
        class: Akyos\SystempayBundle\Service\SystemPay
        arguments: ['@doctrine.orm.entity_manager', '@service_container']

