services:

    akyos.systempay:
        class: Akyos\SystempayBundle\Service\SystemPay
        arguments: ['@doctrine.orm.entity_manager', '@service_container']

    akyos.systempay.twig_extension:
        class: Akyos\SystempayBundle\Twig\TwigExtension
        tags:
            - { name: twig.extension }
